<?php
namespace Migrate\Config;
/**
 * Created by PhpStorm.
 * User: mkkn
 * Date: 2014/12/13
 * Time: 16:50
 */
use FuelPHP\Common\DataContainer;
use Illuminate\Database\Capsule\Manager as Capsule;


class Connection extends Base{

	public function __construct(array $data = null, $readOnly = false)
	{
		parent::__construct($data, $readOnly); // TODO: Change the autogenerated stub
	}


	/**
     * @return Capsule
     */
    public function getCapsule($group,$withDatabase = true){
	    $data = $this->get($group);
	    if($data){
		    $capsule = new Capsule;
		    $capsule->addConnection($data);
//        $capsule->setAsGlobal();
		    return $capsule;
	    }else{
		    throw new \Exception("invalid database setting");
	    }
    }

//    /**
//     * @return Capsule
//     */
//    public function connectWithoutDatabase(){
//        $configuration = $this->all();
//        $configuration["database"] = null;
//        $capsule = new Capsule;
//        $capsule->addConnection($configuration);
////        $capsule->setAsGlobal();
//        return $capsule;
//    }
}
